package Wyjatki;

public class J92 {

		  void canThrowExc() throws Exception { 
		    if (new java.util.Random().nextInt(5) == 0) 
		      throw new Exception(); 
		  } 
		 
		
	
	public static void main(String[] args) {J92 z = new J92();
	try {
		z.canThrowExc();
		z.canThrowExc();
		z.canThrowExc();
		z.canThrowExc();
		z.canThrowExc();
		} catch (Exception e) {
		System.out.println("ogólnie");

	}
		

	}

}
