package Wyjatki;

public class J92 {

		  void canThrowExc() throws Exception { 
		    if (new java.util.Random().nextInt(5) == 0) 
		      throw new Exception(); 
		  } 
		 	
	public static void main(String[] args) {
		J92 z = new J92();
		int i=0;
	try {
		z.canThrowExc();
		i++;
		z.canThrowExc();
		i++;
		z.canThrowExc();
		i++;
		z.canThrowExc();
		i++;
		z.canThrowExc();
		
		} catch (Exception e) {
			e.printStackTrace();// wypisze co to jest za wyj¹tek
		System.out.println("wyj¹tek wywo³any zosta³ po "+i+ " tym losowaniu");

	}
		if(i==6){
			System.out.println("wyj¹tek nie wyst¹pi³");}

	}

}
